# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Harbor agent wrappers that run vendor CLIs in Harbor local mode."""

from __future__ import annotations

import asyncio
import copy
import json
import os
import re
import secrets
import shlex
import tempfile
import uuid
from collections.abc import Awaitable, Callable
from contextlib import suppress
from pathlib import Path, PurePosixPath
from typing import TYPE_CHECKING, Any
from urllib.parse import urlsplit

from harbor.agents.installed.base import NonZeroAgentExitCodeError
from harbor.agents.installed.claude_code import ClaudeCode
from harbor.agents.installed.codex import Codex
from harbor.agents.installed.opencode import OpenCode
from harbor.models.trial.paths import EnvironmentPaths

from skillevaluator.tier3.harbor.nvidia_build_bridge import (
    MAX_REQUESTS_PER_BRIDGE,
    RunningBridge,
    start_in_process_bridge,
)
from skillevaluator.tier3.harbor.sensitive_stdin import (
    NVIDIA_BUILD_STDIN_SENTINEL,
    read_nvidia_build_key_from_stdin,
)

if TYPE_CHECKING:
    from harbor.environments.base import BaseEnvironment

_CODEX_MODEL_ARG_RE = re.compile(r"(?P<prefix>(?:^|\s)--model(?:=|\s+))(?P<model>[^\s]+)(?P<suffix>(?=\s|$))")
_CODEX_REASONING_EFFORT_RE = re.compile(r"^[A-Za-z0-9_-]+$")

_DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1"
_NVIDIA_BUILD_BRIDGE_BASE_URL = "https://integrate.api.nvidia.com/v1"
_NVIDIA_BUILD_BRIDGE_HOST = "127.0.0.1"
_NVIDIA_BUILD_BRIDGE_API_KEY_ENV = "SKILLEVALUATOR_NVIDIA_BUILD_BRIDGE_API_KEY"
_NVIDIA_BUILD_BRIDGE_CLIENT_TOKEN_ENV = "SKILLEVALUATOR_NVIDIA_BUILD_BRIDGE_CLIENT_TOKEN"
_NVIDIA_BUILD_FILE_BACKED_SENTINEL_KEY = "skillevaluator-file-backed-nvidia-key"
_NVIDIA_BUILD_HOST_KEY_FILE_ENV = "SKILLEVALUATOR_NVIDIA_API_KEY_FILE"


async def _await_task_uninterruptibly(
    task: asyncio.Task[Any],
    *,
    preserve_cancellation: bool = True,
) -> Any:
    """Await cleanup work to completion even if cancellation is repeated."""
    cancellation_requested = False
    while True:
        try:
            result = await asyncio.shield(task)
            break
        except asyncio.CancelledError:
            cancellation_requested = True
            if task.done():
                result = task.result()
                break
    if cancellation_requested and preserve_cancellation:
        raise asyncio.CancelledError
    return result


async def _close_running_bridge(
    running: RunningBridge,
    *,
    preserve_cancellation: bool = True,
) -> None:
    close_task = asyncio.create_task(asyncio.to_thread(running.close))
    await _await_task_uninterruptibly(close_task, preserve_cancellation=preserve_cancellation)


def _codex_config_toml(base_url: str) -> str:
    """Generate Codex config for an OpenAI-compatible Responses API endpoint.

    The base URL comes from the caller's OPENAI_BASE_URL so an OSS user points
    Codex at their own OpenAI-compatible Responses provider; no endpoint is
    hardcoded.
    """
    return (
        "# Auto-generated by SkillEvaluator for OpenAI-compatible Responses routing.\n"
        'model_provider = "openai_compatible"\n\n'
        "[model_providers.openai_compatible]\n"
        'name = "OpenAI-compatible provider"\n'
        f'base_url = "{base_url}"\n'
        'env_key = "OPENAI_API_KEY"\n'
        'wire_api = "responses"\n'
    )


def _rewrite_launcher_segment(command: str, rewrite: Callable[[str], str]) -> str:
    """Apply launcher rewrites before the CLI ``--`` prompt separator only."""
    launcher, separator, prompt = command.partition(" -- ")
    if not separator:
        return rewrite(command)
    return f"{rewrite(launcher)}{separator}{prompt}"


class SkillEvaluatorLocalClaudeCode(ClaudeCode):
    """Claude Code wrapper that skips bootstrap install in local mode."""

    _REMOTE_CLAUDE_TMP = PurePosixPath(EnvironmentPaths.agent_dir / "claude-tmp")

    async def install(self, environment: BaseEnvironment) -> None:
        await self.exec_as_agent(environment, command="claude --version")

    def get_version_command(self) -> str | None:
        return "claude --version"

    async def exec_as_agent(
        self,
        environment: BaseEnvironment,
        command: str,
        env: dict[str, str] | None = None,
        cwd: str | None = None,
        timeout_sec: int | None = None,
    ):
        command = _rewrite_launcher_segment(
            command,
            lambda text: text.replace("--permission-mode=bypassPermissions", "--permission-mode=auto"),
        )
        command = f"mkdir -p {shlex.quote(self._REMOTE_CLAUDE_TMP.as_posix())} && {command}"
        routed_env = dict(env or {})
        routed_env["CLAUDE_CODE_TMPDIR"] = self._REMOTE_CLAUDE_TMP.as_posix()
        return await super().exec_as_agent(
            environment,
            command=command,
            env=routed_env,
            cwd=cwd,
            timeout_sec=timeout_sec,
        )


class SkillEvaluatorLocalCodex(Codex):
    """Codex wrapper that uses the managed local CLI and writes CODEX_HOME config."""

    # Harbor's upstream Codex integration uses /tmp/codex-home. In local mode
    # concurrent trials share the host /tmp, so use per-trial log paths instead.
    _REMOTE_CODEX_HOME = PurePosixPath(EnvironmentPaths.agent_dir / "codex-home")
    _REMOTE_CODEX_SECRETS_DIR = PurePosixPath(EnvironmentPaths.agent_dir / "codex-secrets")

    async def install(self, environment: BaseEnvironment) -> None:
        await self.exec_as_agent(environment, command="codex --version")

    def get_version_command(self) -> str | None:
        return "codex --version"

    def _preserve_gateway_model_name(self, command: str, env: dict[str, str] | None) -> str:
        """Undo Harbor's default Codex model truncation when routing through an OpenAI-compatible gateway."""
        model_name = str(self.model_name or "")
        if not model_name or "/" not in model_name or not (env or {}).get("OPENAI_BASE_URL"):
            return command

        short_model = model_name.rsplit("/", 1)[-1]

        def replace(match: re.Match[str]) -> str:
            if match.group("model") != short_model:
                return match.group(0)
            return f"{match.group('prefix')}{model_name}{match.group('suffix')}"

        return _rewrite_launcher_segment(command, lambda text: _CODEX_MODEL_ARG_RE.sub(replace, text))

    def _override_gateway_reasoning_effort(self, command: str, env: dict[str, str] | None) -> str:
        """Override Harbor's Codex reasoning effort for compatible gateways when requested."""
        effort = os.environ.get("SKILL_EVAL_CODEX_REASONING_EFFORT", "").strip()
        base_url = (env or {}).get("OPENAI_BASE_URL") or os.environ.get("OPENAI_BASE_URL")
        if not effort or not base_url:
            return command
        if not _CODEX_REASONING_EFFORT_RE.fullmatch(effort):
            raise ValueError("SKILL_EVAL_CODEX_REASONING_EFFORT must contain only letters, digits, '_' or '-'")
        return _rewrite_launcher_segment(
            command,
            lambda text: re.sub(r"(?<=model_reasoning_effort=)[A-Za-z0-9_-]+", effort, text),
        )

    async def exec_as_agent(
        self,
        environment: BaseEnvironment,
        command: str,
        env: dict[str, str] | None = None,
        cwd: str | None = None,
        timeout_sec: int | None = None,
    ):
        command = _rewrite_launcher_segment(
            command,
            lambda text: text.replace(
                "/tmp/codex-secrets",
                self._REMOTE_CODEX_SECRETS_DIR.as_posix(),
            ),
        )
        command = self._preserve_gateway_model_name(command, env)
        command = self._override_gateway_reasoning_effort(command, env)
        return await super().exec_as_agent(
            environment,
            command=command,
            env=env,
            cwd=cwd,
            timeout_sec=timeout_sec,
        )

    async def run(self, instruction, environment: BaseEnvironment, context) -> None:  # type: ignore[no-untyped-def]
        if getattr(self, "_nvidia_build_bridge_client_env", None) is None:
            config_path = self._REMOTE_CODEX_HOME / "config.toml"
            base_url = os.environ.get("OPENAI_BASE_URL") or _DEFAULT_OPENAI_BASE_URL
            config_text = _codex_config_toml(base_url).replace("'", "'\"'\"'")
            await self.exec_as_agent(
                environment,
                command=(
                    f"mkdir -p {self._REMOTE_CODEX_HOME.as_posix()} "
                    f"{self._REMOTE_CODEX_SECRETS_DIR.as_posix()} && "
                    f"cat > {config_path.as_posix()} <<'EOF'\n"
                    f"{config_text}"
                    "EOF\n"
                ),
            )
        await super().run(instruction=instruction, environment=environment, context=context)


class SkillEvaluatorLocalOpenCode(OpenCode):
    """OpenCode wrapper that skips nvm/npm bootstrap in local mode."""

    _REMOTE_WORKSPACE = PurePosixPath("/workspace")

    async def install(self, environment: BaseEnvironment) -> None:
        await self.exec_as_agent(environment, command="opencode --version")

    def get_version_command(self) -> str | None:
        return "opencode --version"

    def _confined_project_env(self, env: dict[str, str] | None = None) -> dict[str, str]:
        confined = dict(env or {})
        confined.update(
            {
                "OPENCODE_FAKE_VCS": "git",
                "OPENCODE_TEST_HOME": self._REMOTE_WORKSPACE.as_posix(),
                "OPENCODE_DISABLE_PROJECT_CONFIG": "1",
            }
        )
        return confined

    def _nvidia_provider_config_command(self, model_id: str) -> str:
        config: dict[str, object] = {}
        if self.mcp_servers:
            mcp: dict[str, dict[str, object]] = {}
            for server in self.mcp_servers:
                if server.transport == "stdio":
                    cmd_list = [server.command, *server.args] if server.command else []
                    mcp[server.name] = {"type": "local", "command": cmd_list}
                else:
                    mcp[server.name] = {"type": "remote", "url": server.url}
            config["mcp"] = mcp

        config["provider"] = {
            "nvidia": {
                "npm": "@ai-sdk/openai-compatible",
                "name": "NVIDIA Build",
                "models": {model_id: {"name": model_id}},
                "options": {
                    "baseURL": os.environ.get("OPENAI_BASE_URL", ""),
                    "apiKey": "{env:OPENAI_API_KEY}",
                },
            }
        }
        config = self._deep_merge(copy.deepcopy(self._DEFAULT_CONFIG), config)
        config = self._deep_merge(config, self._opencode_config)
        escaped = shlex.quote(json.dumps(config, indent=2))
        return f"mkdir -p ~/.config/opencode && echo {escaped} > ~/.config/opencode/opencode.json"

    async def run(self, instruction, environment: BaseEnvironment, context) -> None:  # type: ignore[no-untyped-def]
        if not self.model_name or "/" not in self.model_name:
            raise ValueError("Model name must be in the format provider/model_name")

        provider, model_id = self.model_name.split("/", 1)
        confinement_env = self._confined_project_env()

        # OpenCode uses / as the project root when no VCS boundary exists. Set
        # up the isolated workspace before either the upstream provider path or
        # the NVIDIA-compatible path can launch it.
        await self.exec_as_agent(
            environment,
            command=f"git -C {self._REMOTE_WORKSPACE.as_posix()} init -q",
            env=confinement_env,
        )

        if provider != "nvidia":
            await super().run(instruction=instruction, environment=environment, context=context)
            return

        instruction = self.render_instruction(instruction)
        env = {key: os.environ[key] for key in ("OPENAI_API_KEY", "OPENAI_BASE_URL") if key in os.environ}
        env = self._confined_project_env(env)

        skills_command = self._build_register_skills_command()
        if skills_command:
            await self.exec_as_agent(environment, command=skills_command, env=env)

        await self.exec_as_agent(
            environment,
            command=self._nvidia_provider_config_command(model_id),
            env=env,
        )

        cli_flags = self.build_cli_flags()
        cli_flags_arg = (cli_flags + " ") if cli_flags else ""
        escaped_instruction = shlex.quote(instruction)
        await self.exec_as_agent(
            environment,
            command=(
                "if [ -f ~/.nvm/nvm.sh ]; then . ~/.nvm/nvm.sh; fi; "
                f"opencode run --model={self.model_name} --format=json "
                f"{cli_flags_arg}--thinking -- {escaped_instruction} "
                "2>&1 </dev/null | tee /logs/agent/opencode.txt"
            ),
            env=env,
        )

    async def exec_as_agent(
        self,
        environment: BaseEnvironment,
        command: str,
        env: dict[str, str] | None = None,
        cwd: str | None = None,
        timeout_sec: int | None = None,
    ):
        # Harbor's Docker image has GNU coreutils and a permissive OpenCode
        # wrapper, but trusted local hosts may have a stock CLI. Keep OpenCode's
        # JSON log capture while avoiding host-only argument failures before the
        # agent can run.
        command = command.replace(
            "| stdbuf -oL tee /logs/agent/opencode.txt",
            "| tee /logs/agent/opencode.txt",
        ).replace(" --dangerously-skip-permissions", "", 1)
        env = self._confined_project_env(env)
        return await super().exec_as_agent(
            environment,
            command=command,
            env=env,
            cwd=cwd,
            timeout_sec=timeout_sec,
        )


class _NvidiaBuildBridgeAgent:
    """Run a Docker-only loopback bridge around Harbor's stock vendor agent."""

    _BRIDGE_SCRIPT = PurePosixPath(EnvironmentPaths.agent_dir / "nvidia-build-bridge.py")
    _BRIDGE_PID = PurePosixPath(EnvironmentPaths.agent_dir / "nvidia-build-bridge.pid")
    _BRIDGE_READY = PurePosixPath(EnvironmentPaths.agent_dir / "nvidia-build-bridge.ready")
    _BRIDGE_LOG = PurePosixPath(EnvironmentPaths.agent_dir / "nvidia-build-bridge.log")

    def _bridge_client_environment(self) -> dict[str, str]:
        raise NotImplementedError

    def _rewrite_bridge_client_command(self, command: str) -> str:
        return command

    @staticmethod
    def _sensitive_exec(environment: BaseEnvironment) -> Callable[..., Awaitable[Any]]:
        """Require a transport that keeps sensitive values out of host argv and logs."""
        sensitive_exec = getattr(environment, "exec_with_sensitive_env", None)
        if not callable(sensitive_exec):
            raise RuntimeError("NVIDIA Build bridge requires an environment with protected sensitive-value transport")
        return sensitive_exec

    async def _prepare_bridge_client(self, environment: BaseEnvironment) -> None:
        """Perform optional agent-specific setup after the bridge is healthy."""

    async def _bridge_raw_exec(
        self,
        environment: BaseEnvironment,
        command: str,
        env: dict[str, str] | None = None,
    ):
        # Docker tasks may declare a non-root USER. Lifecycle files copied by
        # Docker are not guaranteed to be owned by that user, so the private
        # key handoff and cleanup must run through Harbor's root executor.
        return await super().exec_as_root(environment, command=command, env=env)

    @staticmethod
    def _require_success(result: object, operation: str) -> None:
        if getattr(result, "return_code", 0) != 0:
            raise RuntimeError(f"NVIDIA Build bridge {operation} failed")

    @staticmethod
    def _resolve_bridge_api_key() -> str:
        api_key = os.environ.get("NVIDIA_API_KEY", "").strip()
        if api_key == NVIDIA_BUILD_STDIN_SENTINEL:
            return read_nvidia_build_key_from_stdin()
        host_key_file = os.environ.get(_NVIDIA_BUILD_HOST_KEY_FILE_ENV, "").strip()
        if host_key_file:
            try:
                api_key = Path(host_key_file).read_text(encoding="utf-8").strip()
            except OSError as exc:
                raise RuntimeError("NVIDIA Build bridge key handoff file is unavailable") from exc
            if not api_key:
                raise RuntimeError("NVIDIA Build bridge key handoff file is empty")
            return api_key
        if api_key == _NVIDIA_BUILD_FILE_BACKED_SENTINEL_KEY:
            raise RuntimeError(
                f"NVIDIA Build bridge requires {_NVIDIA_BUILD_HOST_KEY_FILE_ENV} for file-backed credentials"
            )
        if not api_key:
            raise RuntimeError("NVIDIA Build bridge requires NVIDIA_API_KEY")
        return api_key

    @staticmethod
    def _bridge_result_stdout(result: object) -> str:
        stdout = getattr(result, "stdout", "")
        if isinstance(stdout, bytes):
            return stdout.decode("utf-8", errors="strict")
        return str(stdout or "")

    @staticmethod
    def _parse_bridge_origin(value: str) -> str:
        origin = value.strip()
        try:
            parsed = urlsplit(origin)
            port = parsed.port
        except ValueError as exc:
            raise RuntimeError("NVIDIA Build bridge returned an invalid dynamic origin") from exc
        expected_origin = f"http://{_NVIDIA_BUILD_BRIDGE_HOST}:{port}" if port is not None else ""
        if (
            parsed.scheme != "http"
            or parsed.hostname != _NVIDIA_BUILD_BRIDGE_HOST
            or parsed.username is not None
            or parsed.password is not None
            or parsed.path
            or parsed.query
            or parsed.fragment
            or port is None
            or origin != expected_origin
        ):
            raise RuntimeError("NVIDIA Build bridge returned an invalid dynamic origin")
        return origin

    def _bridge_origin(self) -> str:
        origin = getattr(self, "_nvidia_build_bridge_origin", None)
        if not origin:
            raise RuntimeError("NVIDIA Build bridge dynamic origin is unavailable")
        return str(origin)

    def _bridge_api_url(self) -> str:
        return f"{self._bridge_origin()}/v1"

    def _bridge_client_token(self) -> str:
        client_token = getattr(self, "_nvidia_build_bridge_client_token", None)
        if not client_token:
            raise RuntimeError("NVIDIA Build bridge client token is unavailable")
        return str(client_token)

    async def _start_bridge(self, environment: BaseEnvironment) -> None:
        sensitive_exec = self._sensitive_exec(environment)
        api_key = self._resolve_bridge_api_key()
        model_name = str(self.model_name or "").strip()
        if not model_name:
            raise RuntimeError("NVIDIA Build bridge requires a selected model")
        private_file_stem = f"/tmp/.skillevaluator-nvidia-build-{uuid.uuid4().hex}"
        key_file = PurePosixPath(f"{private_file_stem}.key")
        client_token_file = PurePosixPath(f"{private_file_stem}.token")
        client_token = secrets.token_urlsafe(32)
        self._nvidia_build_bridge_key_file = key_file
        self._nvidia_build_bridge_client_token_file = client_token_file
        self._nvidia_build_bridge_client_token = client_token
        # From the first upload onward, every exit path owns cleanup. Mark that
        # responsibility before any await can be cancelled.
        self._nvidia_build_bridge_started = True
        try:
            await environment.upload_file(
                Path(__file__).with_name("nvidia_build_bridge.py"), self._BRIDGE_SCRIPT.as_posix()
            )

            # The selected secure Docker environment streams ``env=`` values
            # over Compose stdin. Materialize both secrets only inside the
            # not-yet-exposed task container, then discard the transient names.
            # Do not route this through BaseInstalledAgent._exec: Harbor 0.13.2
            # attaches that helper's raw ``env`` mapping to DEBUG LogRecords,
            # which structured/custom handlers may serialize.
            handoff_result = await sensitive_exec(
                command=(
                    "set -eu; umask 077; "
                    f"printf '%s' \"${{{_NVIDIA_BUILD_BRIDGE_API_KEY_ENV}}}\" > "
                    f"{shlex.quote(key_file.as_posix())}; "
                    f"printf '%s' \"${{{_NVIDIA_BUILD_BRIDGE_CLIENT_TOKEN_ENV}}}\" > "
                    f"{shlex.quote(client_token_file.as_posix())}; "
                    f"unset {_NVIDIA_BUILD_BRIDGE_API_KEY_ENV} {_NVIDIA_BUILD_BRIDGE_CLIENT_TOKEN_ENV}"
                ),
                env={
                    _NVIDIA_BUILD_BRIDGE_API_KEY_ENV: api_key,
                    _NVIDIA_BUILD_BRIDGE_CLIENT_TOKEN_ENV: client_token,
                },
                user="root",
            )
            self._require_success(handoff_result, "secret handoff")

            start_result = await self._bridge_raw_exec(
                environment,
                command=(
                    "set -eu; umask 077; "
                    f"rm -f {shlex.quote(self._BRIDGE_PID.as_posix())} "
                    f"{shlex.quote(self._BRIDGE_READY.as_posix())}; "
                    f"chown 0:0 {shlex.quote(key_file.as_posix())} "
                    f"{shlex.quote(client_token_file.as_posix())}; "
                    f"chmod 600 {shlex.quote(key_file.as_posix())} "
                    f"{shlex.quote(client_token_file.as_posix())}; "
                    "env -u NVIDIA_API_KEY "
                    f"python3 {shlex.quote(self._BRIDGE_SCRIPT.as_posix())} "
                    f"--build-base-url {_NVIDIA_BUILD_BRIDGE_BASE_URL} "
                    f"--api-key-file {shlex.quote(key_file.as_posix())} "
                    f"--client-token-file {shlex.quote(client_token_file.as_posix())} "
                    f"--allowed-model {shlex.quote(model_name)} "
                    f"--max-requests {MAX_REQUESTS_PER_BRIDGE} "
                    "--port 0 "
                    f"--ready-file {shlex.quote(self._BRIDGE_READY.as_posix())} "
                    f"--log-path {shlex.quote(self._BRIDGE_LOG.as_posix())} "
                    ">/dev/null 2>&1 & "
                    f"echo $! > {shlex.quote(self._BRIDGE_PID.as_posix())}"
                ),
                env={},
            )
            self._require_success(start_result, "startup")
            health_result = await self._bridge_raw_exec(
                environment,
                command=(
                    "set -u; "
                    "for attempt in $(seq 1 15); do "
                    f"if [ ! -s {shlex.quote(self._BRIDGE_PID.as_posix())} ]; then exit 1; fi; "
                    f'bridge_pid="$(cat {shlex.quote(self._BRIDGE_PID.as_posix())})"; '
                    'if ! kill -0 "$bridge_pid" 2>/dev/null; then exit 1; fi; '
                    f"if [ -s {shlex.quote(self._BRIDGE_READY.as_posix())} ]; then "
                    "if bridge_origin=$(env -u NVIDIA_API_KEY "
                    f"python3 {shlex.quote(self._BRIDGE_SCRIPT.as_posix())} "
                    f"--check-ready-file {shlex.quote(self._BRIDGE_READY.as_posix())} 2>/dev/null); then "
                    'if ! kill -0 "$bridge_pid" 2>/dev/null; then exit 1; fi; '
                    "printf '%s\n' \"$bridge_origin\"; exit 0; "
                    "fi; fi; "
                    "sleep 1; "
                    "done; echo 'NVIDIA Build bridge health check failed' >&2; exit 1"
                ),
                env={},
            )
            self._require_success(health_result, "health check")
            self._nvidia_build_bridge_origin = self._parse_bridge_origin(self._bridge_result_stdout(health_result))
        except BaseException:
            # Uploads and the detached launch can complete even when their
            # awaiter is cancelled. Complete cleanup despite repeat
            # cancellation, then preserve the original startup failure.
            cleanup_task = asyncio.create_task(self._cleanup_bridge(environment))
            with suppress(BaseException):
                await _await_task_uninterruptibly(cleanup_task, preserve_cancellation=False)
            raise

    async def _cleanup_bridge(self, environment: BaseEnvironment) -> None:
        # The bridge log itself has a fixed sanitized format. Retain it as the
        # sole lifecycle artifact; remove its executable and private metadata.
        key_file = getattr(self, "_nvidia_build_bridge_key_file", None)
        client_token_file = getattr(self, "_nvidia_build_bridge_client_token_file", None)
        private_file_cleanup = "".join(
            f" {shlex.quote(path.as_posix())}" for path in (key_file, client_token_file) if path is not None
        )
        cleanup_complete = False
        try:
            cleanup_result = await self._bridge_raw_exec(
                environment,
                command=(
                    f"if [ -s {shlex.quote(self._BRIDGE_PID.as_posix())} ]; then "
                    f'kill "$(cat {shlex.quote(self._BRIDGE_PID.as_posix())})" 2>/dev/null || true; '
                    "fi; "
                    f"rm -f {shlex.quote(self._BRIDGE_PID.as_posix())} "
                    f"{shlex.quote(self._BRIDGE_READY.as_posix())} "
                    f"{shlex.quote(self._BRIDGE_SCRIPT.as_posix())}{private_file_cleanup}"
                ),
                env={},
            )
            self._require_success(cleanup_result, "cleanup")
            cleanup_complete = True
        finally:
            self._nvidia_build_bridge_origin = None
            if cleanup_complete:
                self._nvidia_build_bridge_started = False
                self._nvidia_build_bridge_key_file = None
                self._nvidia_build_bridge_client_token_file = None
                self._nvidia_build_bridge_client_token = None

    async def exec_as_agent(
        self,
        environment: BaseEnvironment,
        command: str,
        env: dict[str, str] | None = None,
        cwd: str | None = None,
        timeout_sec: int | None = None,
    ):
        client_env = getattr(self, "_nvidia_build_bridge_client_env", None)
        if client_env is None:
            return await super().exec_as_agent(environment, command=command, env=env, cwd=cwd, timeout_sec=timeout_sec)
        sensitive_exec = self._sensitive_exec(environment)
        routed_env = dict(env or {})
        routed_env.update(getattr(self, "_extra_env", {}) or {})
        routed_env.update(client_env)
        routed_env.pop("NVIDIA_API_KEY", None)
        routed_command = self._rewrite_bridge_client_command(command)
        # Harbor 0.13.2 attaches BaseInstalledAgent._exec's merged env to DEBUG
        # LogRecords, which structured/custom handlers may serialize.
        # Call the selected secure environment directly so its stdin transport
        # can protect the per-trial bridge capability as well.
        result = await sensitive_exec(
            command=(f"env -u NVIDIA_API_KEY bash -o pipefail -c {shlex.quote(routed_command)}"),
            env=routed_env,
            cwd=cwd,
            timeout_sec=timeout_sec,
        )
        if result.return_code != 0:
            raise NonZeroAgentExitCodeError(
                f"NVIDIA Build bridge client command failed with exit code {result.return_code}"
            )
        return result

    async def run(self, instruction, environment: BaseEnvironment, context) -> None:  # type: ignore[no-untyped-def]
        self._nvidia_build_bridge_started = False
        self._nvidia_build_bridge_key_file = None
        self._nvidia_build_bridge_client_token_file = None
        self._nvidia_build_bridge_client_token = None
        self._nvidia_build_bridge_origin = None
        run_failed = False
        try:
            await self._start_bridge(environment)
            self._nvidia_build_bridge_client_env = self._bridge_client_environment()
            await self._prepare_bridge_client(environment)
            await super().run(instruction=instruction, environment=environment, context=context)
        except BaseException:
            run_failed = True
            raise
        finally:
            self._nvidia_build_bridge_client_env = None
            if self._nvidia_build_bridge_started:
                try:
                    cleanup_task = asyncio.create_task(self._cleanup_bridge(environment))
                    await _await_task_uninterruptibly(cleanup_task, preserve_cancellation=not run_failed)
                except BaseException:
                    if not run_failed:
                        raise


class SkillEvaluatorNvidiaBuildCodex(_NvidiaBuildBridgeAgent, Codex):
    """Stock Codex CLI routed through the in-trial NVIDIA Build bridge."""

    def _bridge_client_environment(self) -> dict[str, str]:
        return {
            "OPENAI_API_KEY": self._bridge_client_token(),
        }

    def _get_env(self, key: str) -> str | None:
        """Expose the sentinel key while suppressing Codex's legacy base-url config."""
        client_env = getattr(self, "_nvidia_build_bridge_client_env", None)
        if client_env is not None:
            if key == "OPENAI_BASE_URL":
                return None
            if key in client_env:
                return client_env[key]
        return super()._get_env(key)

    async def _prepare_bridge_client(self, environment: BaseEnvironment) -> None:
        config_path = self._REMOTE_CODEX_HOME / "config.toml"
        config_text = _codex_config_toml(self._bridge_api_url())
        await self.exec_as_agent(
            environment,
            command=(
                f"mkdir -p {shlex.quote(self._REMOTE_CODEX_HOME.as_posix())} && "
                f"cat > {shlex.quote(config_path.as_posix())} <<'EOF'\n"
                f"{config_text}"
                "EOF\n"
            ),
        )

    def _rewrite_bridge_client_command(self, command: str) -> str:
        model_name = str(self.model_name or "")
        command = command.replace(
            'openai_base_url = "${OPENAI_BASE_URL}"',
            f'openai_base_url = "{self._bridge_api_url()}"',
        )
        if not model_name or "/" not in model_name:
            return command
        short_model = model_name.rsplit("/", 1)[-1]

        def replace(match: re.Match[str]) -> str:
            if match.group("model") != short_model:
                return match.group(0)
            return f"{match.group('prefix')}{model_name}{match.group('suffix')}"

        return _rewrite_launcher_segment(command, lambda text: _CODEX_MODEL_ARG_RE.sub(replace, text))


class SkillEvaluatorNvidiaBuildClaudeCode(_NvidiaBuildBridgeAgent, ClaudeCode):
    """Stock Claude Code CLI routed through the in-trial NVIDIA Build bridge."""

    def _bridge_client_environment(self) -> dict[str, str]:
        model_name = str(self.model_name or "")
        environment = {
            "ANTHROPIC_API_KEY": self._bridge_client_token(),
            "ANTHROPIC_BASE_URL": self._bridge_origin(),
        }
        if model_name:
            environment.update(
                {
                    "ANTHROPIC_MODEL": model_name,
                    "ANTHROPIC_DEFAULT_SONNET_MODEL": model_name,
                    "ANTHROPIC_DEFAULT_OPUS_MODEL": model_name,
                    "ANTHROPIC_DEFAULT_HAIKU_MODEL": model_name,
                    "CLAUDE_CODE_SUBAGENT_MODEL": model_name,
                }
            )
        return environment


class _LocalHostNvidiaBuildBridgeAgent:
    """Run the authenticated bridge in Harbor's trusted local parent process."""

    async def _start_bridge(self, environment: BaseEnvironment) -> None:
        _ = environment
        api_key = self._resolve_bridge_api_key()
        temp_dir = tempfile.TemporaryDirectory(prefix="skillevaluator-local-nvidia-build-")
        self._nvidia_build_local_temp_dir = temp_dir
        log_path = Path(temp_dir.name) / "nvidia-build-bridge.log"
        self._nvidia_build_local_log_path = log_path
        startup_task = asyncio.create_task(
            asyncio.to_thread(
                start_in_process_bridge,
                api_key=api_key,
                build_base_url=_NVIDIA_BUILD_BRIDGE_BASE_URL,
                log_path=log_path,
                allowed_model=str(self.model_name or "").strip(),
            )
        )
        try:
            running = await asyncio.shield(startup_task)
        except BaseException:
            # ``to_thread`` keeps running if its awaiter is cancelled. Recover
            # the eventual handle and close it before propagating cancellation
            # so no authenticated listener or temporary directory is orphaned.
            try:
                abandoned = await _await_task_uninterruptibly(startup_task, preserve_cancellation=False)
            except BaseException:
                temp_dir.cleanup()
                self._nvidia_build_local_temp_dir = None
                self._nvidia_build_local_log_path = None
            else:
                self._nvidia_build_running_bridge = abandoned
                self._nvidia_build_bridge_client_token = abandoned.client_token
                self._nvidia_build_bridge_origin = abandoned.origin
                self._nvidia_build_bridge_started = True
                try:
                    await _close_running_bridge(abandoned, preserve_cancellation=False)
                except BaseException:
                    # Retain the handle and temp directory so the outer run
                    # finalizer can retry cleanup instead of hiding a listener.
                    pass
                else:
                    temp_dir.cleanup()
                    self._nvidia_build_running_bridge = None
                    self._nvidia_build_local_temp_dir = None
                    self._nvidia_build_local_log_path = None
                    self._nvidia_build_bridge_client_token = None
                    self._nvidia_build_bridge_origin = None
                    self._nvidia_build_bridge_started = False
            raise
        self._nvidia_build_running_bridge = running
        self._nvidia_build_bridge_client_token = running.client_token
        self._nvidia_build_bridge_origin = running.origin
        self._nvidia_build_bridge_started = True

    async def _cleanup_bridge(self, environment: BaseEnvironment) -> None:
        running: RunningBridge | None = getattr(self, "_nvidia_build_running_bridge", None)
        log_path: Path | None = getattr(self, "_nvidia_build_local_log_path", None)
        temp_dir: tempfile.TemporaryDirectory[str] | None = getattr(self, "_nvidia_build_local_temp_dir", None)
        bridge_closed = running is None
        try:
            if running is not None:
                try:
                    await _close_running_bridge(running)
                except asyncio.CancelledError:
                    bridge_closed = running._closed
                    raise
                else:
                    bridge_closed = True
            if log_path is not None and log_path.is_file():
                await environment.upload_file(log_path, _NvidiaBuildBridgeAgent._BRIDGE_LOG.as_posix())
        finally:
            if bridge_closed:
                if temp_dir is not None:
                    temp_dir.cleanup()
                self._nvidia_build_running_bridge = None
                self._nvidia_build_local_log_path = None
                self._nvidia_build_local_temp_dir = None
                self._nvidia_build_bridge_client_token = None
                self._nvidia_build_bridge_origin = None
                self._nvidia_build_bridge_started = False


class SkillEvaluatorLocalNvidiaBuildCodex(
    _LocalHostNvidiaBuildBridgeAgent,
    SkillEvaluatorNvidiaBuildCodex,
    SkillEvaluatorLocalCodex,
):
    """Managed local Codex CLI routed through an authenticated host bridge."""


class SkillEvaluatorLocalNvidiaBuildClaudeCode(
    _LocalHostNvidiaBuildBridgeAgent,
    SkillEvaluatorNvidiaBuildClaudeCode,
    SkillEvaluatorLocalClaudeCode,
):
    """Managed local Claude Code CLI routed through an authenticated host bridge."""


LOCAL_AGENT_IMPORT_PATHS = {
    "claude-code": "skillevaluator.tier3.harbor.local_agents:SkillEvaluatorLocalClaudeCode",
    "codex": "skillevaluator.tier3.harbor.local_agents:SkillEvaluatorLocalCodex",
    "opencode": "skillevaluator.tier3.harbor.local_agents:SkillEvaluatorLocalOpenCode",
}

NVIDIA_BUILD_AGENT_IMPORT_PATHS = {
    "claude-code": "skillevaluator.tier3.harbor.local_agents:SkillEvaluatorNvidiaBuildClaudeCode",
    "codex": "skillevaluator.tier3.harbor.local_agents:SkillEvaluatorNvidiaBuildCodex",
}

NVIDIA_BUILD_LOCAL_AGENT_IMPORT_PATHS = {
    "claude-code": "skillevaluator.tier3.harbor.local_agents:SkillEvaluatorLocalNvidiaBuildClaudeCode",
    "codex": "skillevaluator.tier3.harbor.local_agents:SkillEvaluatorLocalNvidiaBuildCodex",
}
